### ISSUE TITLE
Battles

### ISSUE THREAD

**Issue by GuitarGaming** [foopis23/TSG#5]
When you enter a battle you can still move around without slaying the Thot first

![tsgbattles](https://user-images.githubusercontent.com/32265645/30807455-e419fcd0-a1c7-11e7-8506-01da3d8ad36c.png)

(I hope this works) 
I know its not the cleanest example but you can move between rooms without battling the Thot first.

**Comment by foopis23** [comment]
Thank you for letting me know. I have actually just recently fixed this because i noticed when doing some test the other night. The newest version of the release should have this fixed i am pretty sure!
